
spring:
  application:
    name: RateLimiter
  security:
    user:
      name: user
      password: password
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.filter: INFO
server:
  servlet:
    context-path: /api