spring:
  application:
    name: RateLimiter
  security:
    user:
      name: user
      password: password
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web.filter: INFO
server:
  servlet:
    context-path: /api
glint:
  ratelimiter:
    capacity: 5
    refillRatePerSecond: 0

